### ISSUE TITLE
i dont think this works with slash commands

### ISSUE THREAD

**Issue by luhyeq** [soosBot-com/Pagination#11]
im trying to use this for a slash command and it isnt working lol, idk if im doing anything wrong but id like to know if it works for slash commands.

`await Paginator.Simple().start(interaction.response.send_message(embed = embeds, view=view, ephemeral=True))`

**Comment by sooswastaken** [comment]
What was your issue / mistake?

**Comment by luhyeq** [comment]
> What was your issue / mistake?

i wasnt sure if the pagination works with slash commands, but turns out it does i just dont know how to make it ephemeral rn.
