### ISSUE TITLE
how to make it ephemeral

### ISSUE THREAD

**Issue by luhyeq** [soosBot-com/Pagination#12]
im using the paginator to make a slash command, everything works perfectly and i just need it to be ephemeral

**Comment by soulj8h** [comment]
Try using:

await interaction.response.send_message("your text here", ephemeral=True)

**Comment by luhyeq** [comment]
> Try using:
> 
> await interaction.response.send_message("your text here", ephemeral=True)

Here's my code:
     `await Paginator.Simple(PreviousButton=self.PreviousButton, NextButton=self.NextButton).start(ctx, pages = embeds, ephemeral=True)`

Here's my error:
    `Simple.start() got an unexpected keyword argument 'ephemeral'`

**Comment by sooswastaken** [comment]
The ephemeral argument is passed in the constructor, not the start method.
