### ISSUE TITLE
this doesn't work in a slash command D:

### ISSUE THREAD

**Issue by seriaati** [soosBot-com/Pagination#2]
Since there is no ctx, the paginator doesn't work

**Comment by sooswastaken** [comment]
Your free to update it, I cant right now as I am busy with finals.

**Comment by sooswastaken** [comment]
Fixed in [65d0bfc](https://github.com/soosBot-com/Pagination/commit/65d0bfcbe6b1d47aaf4eb8c55c898ca24e38f5db)
